export const GET_SHIPMENTS_REQUEST = 'GET_SHIPMENTS_REQUEST';
export const GET_SHIPMENTS_SUCCESS = 'GET_SHIPMENTS_SUCCESS';
export const GET_SHIPMENTS_FAILED = 'GET_SHIPMENTS_FAILED';
export const UPDATE_SHIPMENTS_PAGE = 'UPDATE_SHIPMENTS_PAGE';