export const GET_SHIPMENTS_REQUEST = 'GET_SHIPMENTS_REQUEST';
export const GET_SHIPMENTS_SUCCESS = 'GET_SHIPMENTS_SUCCESS';
export const GET_SHIPMENTS_FAILED = 'GET_SHIPMENTS_FAILED';
export const UPDATE_SHIPMENTS_PAGE = 'UPDATE_SHIPMENTS_PAGE';
export const ORDER_BY_SHIPMENTS = 'ORDER_BY_SHIPMENTS';
export const GET_SEARCH_DATA_REQUEST = 'GET_SEARCH_DATA_REQUEST';
export const GET_SEARCH_DATA_SUCCESS = 'GET_SEARCH_DATA_SUCCESS';
export const GET_SEARCH_DATA_FAILED = 'GET_SEARCH_DATA_FAILED';